spring:
  application.name: MonkeyNotes
  resources:
    static-locations=classpath:static/:
  datasource:
    url: jdbc:postgresql://mn-db:5432/monkey_db
    username: monkey_user
    password: monK3Y__42_Pa55w0rD
    hikari.auto-commit: false
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.time_zone: UTC
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

app:
  security:
    cors.origin: ${CORS_DOMAINS}
  dry-run: false
  drive:
    auth:
      refresh-token: 3500
      client-id: ${GDRIVE_CLIENT_ID}
      client-secret: ${GDRIVE_SECRET}
  changes:
    listen.on-startup.enabled: true
    expiration: 3000
    flush: 5
  openai:
    api: ${OPENAI_API_KEY}
    models:
      available: gpt-5=High (gpt-5),gpt-5-mini=Medium (gpt-5-mini),gpt-4.1=Low (gpt-4.1)
      default: gpt-4.1
      instructions: You are an expert document analysis assistant. You will receive * a user question, * conversation language (default fr might change upon user request) * one or more document chunks retrieved from a knowledge base.
  qwen:
    url: https://dashscope-intl.aliyuncs.com/compatible-mode/v1/chat/completions
    key: ${QWEN_API_KEY}
  paths:
    user_data: /mn_data
  url:
    frontend: ${YOUR_DOMAIN}
    self: ${YOUR_DOMAIN_API} #NOTE THE TRAILING API (nginx proxying)
  notify:
    path: /notify
  oauth-callback:
    path: /grant-callback
  defaults:
    image:
      resize:
        max:
          width: 1200
          height: 1000
      crop:
        enabled: true
        padding: 10
    qwen:
      prompt: You are an expert OCR engine specialized in handwritten documents.  Your task is to accurately transcribe the provided image into plain text
      models:
        #qwen-vl-max (top)
        #qwen-vl-plus (balanced)
        #qwen-vl-ocr (specialized)
        #qwen3-vl-max-latest (flaship)
        #qwen3-vl-plus (balanced)
        #qwen3-vl-flash (fast/cheap)
        #qwen3.5-plus (newest)
        #qwen3.5-flash (fast/cheap)
        available: qwen-vl-max=Top(qwen-vl-max),qwen-vl-plus=Balanced(qwen-vl-plus),qwen-vl-ocr=Specialized(qwen-vl-ocr)
        default: qwen-vl-ocr
      max-tokens: 5000
    ai:
      connect-timeout: 3000
      read-timeout: 180000

  email:
    enable: ${EMAIL_ENABLE}
    sender: ${EMAIL_SENDER}
    mailjet.apikey:
      public: ${MAILJET_PUBLIC}
      private: ${MAILJET_PRIVATE}
    reports.delay: 5

#Tooling Spring Boot Starter config
tooling :
  error :
    stacktrace :
      include : true
      log : true

#Logger config
logging:
  level:
    ROOT: INFO